German translations
sumpfork/dominiontabs pull request #365
Opened 2022-01-27 20:53 UTC by AlessandroFasse

Added the translation for the Expansion "Menagerie" in German and also the missing "Kaptain Tobias". 

Also I added that you can run the tests on Windows. There was an issue with the path separator `\` on Windows, which was miss interpreted. 

I hope everything else is with respect to the guidelines.

2022-01-27 21:33 UTC, sumpfork requested changes
Thanks for all the work!

I just started looking at this - haven't actually run it yet to check the output, but there seem to be a couple minor spelling/punctuation problems. I didn't go through all the text, but maybe you could check the rest for similar issues?

2022-01-27 21:33 UTC, sumpfork commented on card_db_src/de/sets_de.json
> +        "set_text": "Dein Dominion, das ist es, was du aufbauen willst Diesmal mit Tieren! Von jedem kann man etwas lernen, etwa, wie man wirklich weit spucken kann oder welche Sorte Gras am besten s
Punkt fehlt nach them ersten Satz. Komma vor "..., Den Fuchs" sollte ein Punkt sein. "irgendjemanden" -> "irgend jemanden". Komma nach "Erweiterung" sollte ein Punkt sein.

2022-01-27 21:33 UTC, sumpfork commented on card_db_src/de/sets_de.json
> +        "set_text": "Die Promotionskarten sind offizielle <i>Dominion</i> Königreichkarten und Events, die zu keiner Erweiterung gehören. In der Regel werden diese Karten wärend Events (Origins or Ge
"wärend" -> "während"

2022-01-27 22:26 UTC, AlessandroFasse commented on card_db_src/de/sets_de.json
> +        "set_text": "Dein Dominion, das ist es, was du aufbauen willst Diesmal mit Tieren! Von jedem kann man etwas lernen, etwa, wie man wirklich weit spucken kann oder welche Sorte Gras am besten s
Danke

2022-01-27 22:26 UTC, AlessandroFasse commented on card_db_src/de/sets_de.json
> +        "set_text": "Die Promotionskarten sind offizielle <i>Dominion</i> Königreichkarten und Events, die zu keiner Erweiterung gehören. In der Regel werden diese Karten wärend Events (Origins or Ge
fixed

2022-01-27 22:27 UTC, AlessandroFasse commented
Is also went now with a type check over all cards and found a lot of other mistakes in other editions as well

2022-01-28 07:17 UTC, AlessandroFasse commented
Fixed the typo

2022-02-06 21:44 UTC, merged